apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: tnode
  name: node-controller
spec:
  replicas: 1
  selector:
    name: tnode
  template:
    metadata:
      labels:
        name: tnode
    spec:
      containers:
      - image: tjskrishna/nodejs-web
        name: tnode
        ports:
        - name: tnode
          containerPort: 3000
