---
  apiVersion: "v1"
  kind: "ReplicationController"
  metadata: 
    name: "blah"
    namespace: "7mgxwvnnszaefjrdljr8lu"
  spec: 
    selector: 
      name: "blah"
    template: 
      metadata: 
        labels: 
          name: "blah"
      spec: 
        containers: 
          - 
            name: "blah"
            image: "tjskrishna/nodejs-web"
            ports: 
              - 
                containerPort: 3000
                name: "w"
                protocol: "TCP"
